#!/usr/bin/python3 -u

import os.path

import zebr0

if __name__ == "__main__":
    argparser = zebr0.ArgumentParser()
    args = argparser.parse_args()

    if not os.path.exists(args.conf):
        os.makedirs(args.conf)

    for parameter in ["url", "project", "stage"]:
        with open(os.path.join(args.conf, parameter), "w") as file:
            file.write(getattr(args, parameter))
