#!/usr/bin/python3 -u

import pathlib
import sys

import zebr0


def config():
    path = pathlib.Path(args.conf)
    path.mkdir(parents=True, exist_ok=True)

    for parameter in ["url", "project", "stage"]:
        path.joinpath(parameter).write_text(getattr(args, parameter))


def get():
    sys.stdout.write(zebr0.Client(args).get(args.key, args.default, args.render, args.strip))


argparser = zebr0.ArgumentParser()
subparsers = argparser.add_subparsers()

subparser_config = subparsers.add_parser("config")
subparser_config.set_defaults(command=config)

subparser_get = subparsers.add_parser("get")
subparser_get.add_argument("key")
subparser_get.add_argument("-d", "--default")
subparser_get.add_argument("--render", action="store_true")
subparser_get.add_argument("--strip", action="store_true")
subparser_get.set_defaults(command=get)

args = argparser.parse_args()
args.command()
