#!/usr/bin/python3 -u

import argparse
import configparser
import subprocess

import zebr0lib


def edit(filename):
    parser = configparser.ConfigParser()
    parser[zebr0lib.CONFIG] = {
        zebr0lib.BASE_URL: zebr0lib.base_url
    }

    with open(filename, "w") as file:
        parser.write(file)
    subprocess.call(["/usr/bin/editor", filename])


if __name__ == "__main__":
    argparser = argparse.ArgumentParser(description="")
    argparser.add_argument("filename", nargs="?", default=zebr0lib.DEFAULT_PATH, help="")

    args = argparser.parse_args()

    edit(args.filename)
